SITE:
    Local: '127.0.0.1:8888'
    Remote:
        Url: 'https://rdm-upei.researchspaces.ca'
        Path: user
PORT: 8000
BSREWRITE:
    Css:
        Match: "/themes/contrib/edux/css/"
        Replace: "/css/"
    Js:
        Match: "/themes/contrib/edux/js/"
        Replace: "/js/"
PATHS:
    Watch:
      #changes in these compiled files trigged reload
      - ./css/*.css
      - ./js/*.js
    Scss:
        Dir: sass
        #FileName: app.scss
        Libraries:
           #- css/libraries/guff
           #- css/libraries/typeplate
    Css:
        Dir: css
        #FileName: app.css
    Js:
        Src: ./js/src/*.js
        Dest: js
        FileName: 'ia-islandimagined.behaviors.js'
    Img:
        Src: img/src
        Dest: img

